### ISSUE TITLE
Clean download history on browser start

### ISSUE THREAD

**Issue by CodingMarkus** [fuzzykiller/download-cleaner-lite#1]
It may not be possible to detect when the app quits, but it is certainly possible to detect when the app starts as at some point your extension will be initialized during startup, right? So how about an option to delete download history on start up? That would almost have the same effect to me as cleaning history is not a privacy feature for me, it's just for reducing UI clutter.

**Comment by btzdnl** [comment]
Thanks for the suggestion! It’s a good idea in general. However, the `downloads` API does not provide access to downloads across browser restarts. In essence, it’s like this: Is it gone from the downloads popup? It’s no longer a download.

Instead, those downloads are saved in the browser history. However, the `history` API does not provide a way to query the “real” [transition type](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsINavHistoryService#Transition_type_constants).

So, not possible. Sorry! 🙁

**Comment by Azlond** [comment]
[Bugzilla 1255507](https://bugzilla.mozilla.org/show_bug.cgi?id=1255507) might be worth watching for this. 
It is, however, unassigned as of now. So probably not something to be implemented anytime soon.

**Comment by CodingMarkus** [comment]
Okay, but extensions can store persistent data across app restarts, correct? So how about storing enough persistent information to identify a download as soon as the download begins? When the download is removed by the extension itself or by any other means (manually by the user), the stored information is discarded for that download, too. On app start the app checks if "Remove Downloads on Start" is checked and if it is, it attempts to remove all remembered downloads (which not be there anymore, so it's best effort). Finally the stored information is discarded on every app start, as it is only required for this initial removal (this will also happen if the option is not even checked to remove on app start).

Here's pseudo code (no particular programming language, but you'll get what I mean)

```
func getRemoveOnAppStartOption ( ) {
  return ...; /* Fetch the user configured option whether to do that or not */
}

func getAutoRemoveTime ( ) {
  return ...; /* Fetch the user configured time from the preferences */
}

func rememberDownload ( download ) {
  /* Remember the download in such a way that is survives app restarts */
}

func forgetDownload ( download ) {
  /* Remove all remembered information about download */
}

func onDownloadStart ( download ) { 
  rememberDownload(download); 
}

func onDownloadFinish ( download ) { 
  startTimer(getAutoRemoveTime(), removeDownload, download); 
}

/* Triggered whenever a download is removed, also when removed by user */
func onDownloadRemove (download ) { 
  forgetDownload(download); 
}

func removeDownload ( download ) { 
  /* User may already have removed download when this is called */
  /* Triggers onDownloadRemove (), if something is removed */ 
  firefoxRemoveDownload(download); 
}

func onAppStart ( ) {
  if (getRemoveOnAppStartOption()) {
    var allRememberedDownloads = ...; /* Get all we have */
    for (download in allRememberedDownloads) {
      removeDownload(download);
    }
  }
  /* Forget all remembered downloads here */
}
```

**Comment by btzdnl** [comment]
That looks like a feasible solution. It unfortunately does not remove downloads from third-party extensions like Download Statusbar.

**Comment by CodingMarkus** [comment]
But will the current code remove downloads from Download Statusbar? I don't know as I don't use that extension. And if the current code does not, then I fail to see the problem, as then this is a general issue the extension has (or not issue, let's say a "limitation"), so implementing this feature won't make the extension "any worse". Otherwise I wonder how the timed removal is able to do something that cannot be done after app restart anymore. I understand that you cannot get the information what kind of item a history item really is  but isn't it possible to identify such an item across app restarts (e.g. by URL or some other reference) assuming that you knew the kind at some time in the past? Sorry, I'm not trying to be annoying here, I'm just a developer myself, so naturally I always think "Okay, if that was my extension, how could I maybe solve that problem" - I just suck horribly at JavaScript 😅

**Comment by btzdnl** [comment]
Yes, they sort-of communicate using `Downloads.jsm` (the backend of the `browser.downloads` API). Download Statusbar probably remembers downloads in its private storage, too.

I’m currently implementing, however it’ll take some restructuring to implement this in a non-hacky way.

**Comment by btzdnl** [comment]
The next release, [1.3](https://github.com/fuzzykiller/download-cleaner-lite/tree/version/1.3), implements the “remove on startup” option. 🎉
