### ISSUE TITLE
[feature request] Consider cancelled downloads complete

### ISSUE THREAD

**Issue by DragonJTS** [fuzzykiller/download-cleaner-lite#11]
Would it be possible to add a separate option to toggle whether or not manually cancelled downloads are considered complete, so that they can be automatically removed while failed downloads remain?

**Comment by btzdnl** [comment]
According to the API documentation this should be possible, yes. I’ll try to implement it soon.

**Comment by btzdnl** [comment]
Version 2.3 of the add-on is now live on AMO. Give it a try to see if it meets your requirements! If not, we’ll reopen this issue.

**Comment by DragonJTS** [comment]
Exactly what I was looking for, thanks.
