### ISSUE TITLE
Bad readability with dark themes

### ISSUE THREAD

**Issue by BooSN** [fuzzykiller/download-cleaner-lite#2]
Options are invisible on dark themes like FT DeepDark

**Comment by btzdnl** [comment]
Please don’t report multiple issues at once. I will only track the first issue here.

**Comment by btzdnl** [comment]
Support for themes is impossible until [1275287 – Implement `chrome_style` in options V2 API.](https://bugzilla.mozilla.org/show_bug.cgi?id=1275287) lands. It will be a breaking change, so I won’t publish it until Firefox 55 is available.

**Comment by BooSN** [comment]
Why not just use a white background with black text?

**Comment by btzdnl** [comment]
The current style is made to feel “native” with default themes on all platforms. I don’t want to change that.

**Comment by btzdnl** [comment]
Support for full themes is gone and the issue above is implemented (though it doesn’t help anyway). The current type of themes doesn’t affect the settings page.

Closing.
