### ISSUE TITLE
Paused/failed downloads are cleaned

### ISSUE THREAD

**Issue by ghost** [fuzzykiller/download-cleaner-lite#3]
I was not expecting the extension to clean out paused downloads. In removeDownloads:
```
// Skip in-progress downloads
if (download.state === "in_progress") {
  continue;
}
```

Could/should that either check for 'complete', or just additionally exclude 'interrupted' if you want to leave it open to cleaning out future state constants?

`if (download.state !== "complete") {`
or
`if (download.state === "in_progress" || download.state === "interrupted") {`

As-is, failed/paused downloads just vanish when using the delay option.

**Comment by btzdnl** [comment]
Hm, you’re right, the current way of checking is not correct. Though I’d argue that interrupted downloads should in fact be removed. I’ll probably add a switch to control this behavior.

**Comment by btzdnl** [comment]
This issue is fixed in the upcoming (AMO review pending) version 2.0 of the extension.

**Comment by ghost** [comment]
Works great, and thank you for the extra effort to make it configurable (and for the extension itself, solves a long-time irritation with Firefox).
