### ISSUE TITLE
Allow for instant removal

### ISSUE THREAD

**Issue by btzdnl** [fuzzykiller/download-cleaner-lite#5]
Downloads are currently removed with a delay of at least one minute. When the delay is set to 0, the download should be removed right away.

**Comment by btzdnl** [comment]
Implemented in ed39a1d5951bb0999536f7c4ebb7d32e1fb24edf

**Comment by chaynes112** [comment]
I downloaded the ZIP file for ed39a1d. How do I 'apply' the update?

**Comment by btzdnl** [comment]
You cannot. Firefox is “hard-wired” to only accept extension updates from [addons.mozilla.org](https://addons.mozilla.org).

For development, you can load temporary extensions.

**Comment by chaynes112** [comment]
Are there plans to include the 0 delay in the current version?

**Comment by btzdnl** [comment]
A new version will be released once #4 is fixed.

**Comment by chaynes112** [comment]
Ok, thanks.

**Comment by btzdnl** [comment]
Now available in version 2.1.

**Comment by chaynes112** [comment]
Thank you.

-------- Original message --------From: Daniel <notifications@github.com> Date: 9/12/20  5:10 PM  (GMT-05:00) To: fuzzykiller/download-cleaner-lite <download-cleaner-lite@noreply.github.com> Cc: chaynes112 <chaynes112@aol.com>, Comment <comment@noreply.github.com> Subject: Re: [fuzzykiller/download-cleaner-lite] Allow for instant removal
  (#5) 
Now available in version 2.1.
