### ISSUE TITLE
Doesn’t work with Firefox 70

### ISSUE THREAD

**Issue by btzdnl** [fuzzykiller/download-cleaner-lite#6]
On Firefox 70(b5), there appears to be a regression in the `downloads` API. The extension does not receive any notifications about new or changed downloads.

When a download is started, the browser console displays these messages:

![browser console](https://user-images.githubusercontent.com/664869/64765818-22834a00-d545-11e9-82c2-6271f0009a64.png)

Further investigation is required.

**Comment by btzdnl** [comment]
Testing with the [test-firefox70-regression branch](https://github.com/fuzzykiller/download-cleaner-lite/tree/test-firefox70-regression) has revealed that the `onCreated` event no longer works. I will file a bug with Mozilla.

**Comment by btzdnl** [comment]
Someone was faster in reporting it: [1581270](https://bugzilla.mozilla.org/show_bug.cgi?id=1581270)

**Comment by EverEve** [comment]
Hello, it seems that the problem is solved in Firefox 71

**Comment by btzdnl** [comment]
That’s right, it’s working again in Firefox Developer Edition. According to [the non-duplicate issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1576508) it should even be fixed in Firefox 70, though probably not 70.0.0.

Nothing more to do here except wait for the Firefox update.
